### ISSUE TITLE
[问题]探索RxJS-CoreConcept#处理一系列的异步请求队列

### ISSUE THREAD

**Issue by xaclincoln** [ecmadao/Coding-Guide#1]
使用RxJS处理4G文件的读取加密写入时，尽管不需要申请一块连续的4G内存，但仍然需要申请许多的64k内存块，这样仍会对GC造成比较大的压力。个人认为使用NodeJs中的stream.pipe来实现这个场景更为合适，不知道我的理解是否正确？

**Comment by ecmadao** [comment]
@xaclincoln 
我觉得你的想法应该是对的，毕竟多次 IO 也会给系统造成压力，而 node 本身 IO 异步，而且在底层使用了 C，一定会比我们自己手写的要好。个人觉得 RxJS 的主要应用还是更偏向于前端一些，如果后端是 node 的话，应该很多功能可以完爆 Rx 😂

**Comment by bakso** [comment]
后端在构建消息系统的时候也可以用Rx哦

**Comment by ecmadao** [comment]
@bakso 消息系统？好像很有意思，求具体案例~
