### ISSUE TITLE
【问题】有什么将网页转换为 PDF 的方法？

### ISSUE THREAD

**Issue by ecmadao** [ecmadao/Coding-Guide#2]
经过调研，我目前发现的方法如下（使用 Node ）：

- 利用 [phantom.js](http://phantomjs.org/) 的 render

- [phantomjs-node](https://github.com/amir20/phantomjs-node)，对 phantom.js 进行了一层封装

这是我尝试的目前效果最好的方法，可以直接自行封装一个脚本，由前端调用 API 后触发。但渲染速度不尽人意，不过也应该有一些优化的空间。

```javascript
// demo
const phantom = require('phantom');

(async function() {
    const instance = await phantom.create();
    const page = await instance.createPage();

    await page.property('viewportSize', {width: 1024, height: 600});
    const status = await page.open('https://stackoverflow.com/');
    console.log(`Page opened with status [${status}].`);

    await page.render('stackoverflow.pdf');
    console.log(`File created at [./stackoverflow.pdf]`);

    await instance.exit();
}());
```

- [node-webshot](https://github.com/brenden/node-webshot)

生成网页截屏。但只能是 png、jpg、jpeg 形式，且无法滚屏截图，只能指定图片高度或者按照窗口大小截取（目前没有找到合适的方式）

```javascript
// demo
var webshot = require('webshot');

webshot('google.com', 'google.png', function(err) {
  // screenshot now saved to google.png
});
```

- [node-html-pdf](https://github.com/marcbachmann/node-html-pdf)

暂时还没有尝试，看见在 stackoverflow 上有人推荐，也有人反馈说该库有很奇怪的 bug

- [dom-to-image](https://github.com/tsayen/dom-to-image)

相对于上面的方法，该库是在前端调用，将一个指定的 DOM 转为 base64 格式的图片，并可以保留其样式。但缺点很明显，由于是前端使用，在 DOM 数目较多时会有明显的卡顿，体验不好。

```javascript
// demo
domtoimage.toJpeg(document.getElementById('my-node'))
    .then(function (dataUrl) {
        var link = document.createElement('a');
        link.download = 'my-image-name.jpeg';
        link.href = dataUrl;
        link.click();
    });
```

- [stackoverflow 上的讨论 - HTML to PDF with Node.js](http://stackoverflow.com/questions/14552112/html-to-pdf-with-node-js)

	- phantomjs
	- window.print()
	- [htmltocanvas](http://html2canvas.hertzen.com/) 或者 [rasterizeHTML](https://github.com/cburgmer/rasterizeHTML.js)，然后 [jsPDF](http://parall.ax/products/jspdf)
	- node-html-pdf

**Comment by ecmadao** [comment]
有很多 chrome 插件可以将页面转为 PDF，但无法完成自动化。我目前用的最好的插件是这个：[FireShot](https://chrome.google.com/webstore/detail/take-webpage-screenshots/mcbpblocgmgfnpjjppndjkmgjaogfceg)，但是它是在自己的 server 上生成的 PDF ，无法查看具体实现，而官方的 API 的话使用是要收费的。

**Comment by lau-jay** [comment]
赞

**Comment by ecmadao** [comment]
[hacknical](https://www.github.com/ecmadao/hacknical) 最终采用 phantomJS 的方式在服务端渲染页面到 PDF
