### ISSUE TITLE
commonChunkPlugin中的children配置是什么意思

### ISSUE THREAD

**Issue by liangklfangl** [ecmadao/Coding-Guide#3]
下面这段代码为什么没有产生一个vendor.bundle.js在output.path路径下，但是去掉children又是可以产生的
`new webpack.optimize.CommonsChunkPlugin({
                filename:'vendor.bundle.js',
                name:      'vendor', // Move dependencies to our main file
                children:  true, // Look for common dependencies in all children,
                minChunks: 2, // How many times a dependency must come up before being extracted
            })`

**Comment by ecmadao** [comment]
@liangklfangl 

先说两个个人理解：

- `minChunks` 参数代表至少有多少依赖重复时，该依赖会被抽取到 common chunk 中。
- `children` 参数设置为 true 时，代表会检查所有文件的依赖，而不仅仅是入口文件里的依赖。

由此，举个例子，我们有 `a.js`，`b.js`，`c.js`，`d.js` 四个文件，其中 `a.js` 和 `b.js` 是入口文件。

```javascript
// a.js
require('c.js');
```

```javascript
// b.js
require('c.js');
```

```javascript
// c.js
require('d.js');
```

```javascript
// d.js
console.log('I am d.js file.');
```

当**没有设置** `children: true`，且 `minChunks` 设置为 2 时，两个入口文件有共同依赖 `c.js`，且依赖次数为 2，因此，可以抽取出 common chunk；而 `children: true` 且 `minChunks: 2` 时，一共有 4 个文件接收检查，但是 4 个文件并没有共同依赖、且被依赖次数大于等于 2 次的文件，所以，此时是无法提取 common chunk 的。

**Comment by liangklfangl** [comment]
也就是说，如果没有设置children：true其实是以入口文件开始查找依赖的module的，其实际就是查找多个入口文件的公有module。而如果设置了children:true，实际上就是查找每一个chunk中各自依赖的module了，只有在这个chunk中依赖的同一个module超过指定的次数才会被提取。不知道这样理解对不对？

**Comment by ecmadao** [comment]
@liangklfangl 
嗯，我自己在使用的时候就是这么理解的

**Comment by liangklfangl** [comment]
ok，thx

**Comment by liangklfangl** [comment]
那这种children的用法应该在code splitting的时候才会用到吧
